
// types for user
export const USER_REGISTER_START = "USER_REGISTER_START";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_GET_START = "USER_GET_START";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";
export const USER_GET_FAIL = "USER_GET_FAIL";

export const USER_PROFILE_UPDATE_START = "USER_PROFILE_UPDATE_START";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_FAIL = "USER_PROFILE_UPDATE_FAIL";

// types for management
export const MANAGEMENT_GET_LOCATIONS_START = "MANAGEMENT_GET_LOCATIONS_START";
export const MANAGEMENT_GET_LOCATIONS_SUCCESS = "MANAGEMENT_GET_LOCATIONS_SUCCESS";
export const MANAGEMENT_GET_LOCATIONS_FAIL = "MANAGEMENT_GET_LOCATIONS_FAIL";

export const MANAGEMENT_LOCATIONS_CREATE_START = "MANAGEMENT_LOCATIONS_CREATE_START";
export const MANAGEMENT_LOCATIONS_CREATE_SUCCESS = "MANAGEMENT_LOCATIONS_CREATE_SUCCESS";
export const MANAGEMENT_LOCATIONS_CREATE_FAIL = "MANAGEMENT_LOCATIONS_CREATE_FAIL";

export const MANAGEMENT_LOCATIONS_UPDATE_START = "MANAGEMENT_LOCATIONS_UPDATE_START";
export const MANAGEMENT_LOCATIONS_UPDATE_SUCCESS = "MANAGEMENT_LOCATIONS_UPDATE_SUCCESS";
export const MANAGEMENT_LOCATIONS_UPDATE_FAIL = "MANAGEMENT_LOCATIONS_UPDATE_FAIL";

export const MANAGEMENT_COURTS_CREATE_START = "MANAGEMENT_COURTS_CREATE_START";
export const MANAGEMENT_COURTS_CREATE_SUCCESS = "MANAGEMENT_COURTS_CREATE_SUCCESS";
export const MANAGEMENT_COURTS_CREATE_FAIL = "MANAGEMENT_COURTS_CREATE_FAIL";

export const MANAGEMENT_COURTS_UPDATE_START = "MANAGEMENT_COURTS_UPDATE_START";
export const MANAGEMENT_COURTS_UPDATE_SUCCESS = "MANAGEMENT_COURTS_UPDATE_SUCCESS";
export const MANAGEMENT_COURTS_UPDATE_FAIL = "MANAGEMENT_COURTS_UPDATE_FAIL";

export const MANAGEMENT_GET_SCHEDULE_START = "MANAGEMENT_GET_SCHEDULE_START";
export const MANAGEMENT_GET_SCHEDULE_SUCCESS = "MANAGEMENT_GET_SCHEDULE_SUCCESS";
export const MANAGEMENT_GET_SCHEDULE_FAIL = "MANAGEMENT_GET_SCHEDULE_FAIL";

export const MANAGEMENT_GET_LOCATION_COURTS_START = "MANAGEMENT_GET_LOCATION_COURTS_START";
export const MANAGEMENT_GET_LOCATION_COURTS_SUCCESS = "MANAGEMENT_GET_LOCATION_COURTS_SUCCESS";
export const MANAGEMENT_GET_LOCATION_COURTS_FAIL = "MANAGEMENT_GET_LOCATION_COURTS_FAIL";

export const MANAGEMENT_GET_ANALYTICS_START = "MANAGEMENT_GET_ANALYTICS_START";
export const MANAGEMENT_GET_ANALYTICS_SUCCESS = "MANAGEMENT_GET_ANALYTICS_SUCCESS";
export const MANAGEMENT_GET_ANALYTICS_FAIL = "MANAGEMENT_GET_ANALYTICS_FAIL";

export const MANAGEMENT_COURTS_DELETE_START = "MANAGEMENT_COURTS_DELETE_START";
export const MANAGEMENT_COURTS_DELETE_SUCCESS = "MANAGEMENT_COURTS_DELETE_SUCCESS";
export const MANAGEMENT_COURTS_DELETE_FAIL = "MANAGEMENT_COURTS_DELETE_FAIL";

export const MANAGEMENT_COURTS_SCHEDULE_CREATE_START = "MANAGEMENT_COURTS_SCHEDULE_CREATE_START";
export const MANAGEMENT_COURTS_SCHEDULE_CREATE_SUCCESS = "MANAGEMENT_COURTS_SCHEDULE_CREATE_SUCCESS";
export const MANAGEMENT_COURTS_SCHEDULE_CREATE_FAIL = "MANAGEMENT_COURTS_SCHEDULE_CREATE_FAIL";

export const MANAGEMENT_COURTS_SCHEDULE_UPDATE_START = "MANAGEMENT_COURTS_SCHEDULE_UPDATE_START";
export const MANAGEMENT_COURTS_SCHEDULE_UPDATE_SUCCESS = "MANAGEMENT_COURTS_SCHEDULE_UPDATE_SUCCESS";
export const MANAGEMENT_COURTS_SCHEDULE_UPDATE_FAIL = "MANAGEMENT_COURTS_SCHEDULE_UPDATE_FAIL";

export const MANAGEMENT_COURTS_SCHEDULE_GET_START = "MANAGEMENT_COURTS_SCHEDULE_GET_START";
export const MANAGEMENT_COURTS_SCHEDULE_GET_SUCCESS = "MANAGEMENT_COURTS_SCHEDULE_GET_SUCCESS";
export const MANAGEMENT_COURTS_SCHEDULE_GET_FAIL = "MANAGEMENT_COURTS_SCHEDULE_GET_FAIL"

// common types for users, companies
export const COMMON_GET_COMPANIES_START = "COMMON_GET_COMPANIES_START";
export const COMMON_GET_COMPANIES_SUCCESS = "COMMON_GET_COMPANIES_SUCCESS";
export const COMMON_GET_COMPANIES_FAIL = "COMMON_GET_COMPANIES_FAIL";

export const COMMON_GET_COURT_TYPES_START = "COMMON_GET_COURT_TYPES_START";
export const COMMON_GET_COURT_TYPES_SUCCESS = "COMMON_GET_COURT_TYPES_SUCCESS";
export const COMMON_GET_COURT_TYPES_FAIL = "COMMON_GET_COURT_TYPES_FAIL";

export const COMMON_GET_LOCATIONS_START = "COMMON_GET_LOCATIONS_START";
export const COMMON_GET_LOCATIONS_SUCCESS = "COMMON_GET_LOCATIONS_SUCCESS";
export const COMMON_GET_LOCATIONS_FAIL = "COMMON_GET_LOCATIONS_FAIL";

export const COMMON_GET_COURTS_START = "COMMON_GET_COURTS_START";
export const COMMON_GET_COURTS_SUCCESS = "COMMON_GET_COURTS_SUCCESS";
export const COMMON_GET_COURTS_FAIL = "COMMON_GET_COURTS_FAIL";

export const COMMON_GET_COURT_DETAIL_START = "COMMON_GET_COURT_DETAIL_START";
export const COMMON_GET_COURT_DETAIL_SUCCESS = "COMMON_GET_COURT_DETAIL_SUCCESS";
export const COMMON_GET_COURT_DETAIL_FAIL = "COMMON_GET_COURT_DETAIL_FAIL";

export const COMMON_GET_LOCATION_DETAIL_START = "COMMON_GET_LOCATION_DETAIL_START";
export const COMMON_GET_LOCATION_DETAIL_SUCCESS = "COMMON_GET_LOCATION_DETAIL_SUCCESS";
export const COMMON_GET_LOCATION_DETAIL_FAIL = "COMMON_GET_LOCATION_DETAIL_FAIL";

export const COMMON_GET_CITIES_START = "COMMON_GET_CITIES_START";
export const COMMON_GET_CITIES_SUCCESS = "COMMON_GET_CITIES_SUCCESS";
export const COMMON_GET_CITIES_FAIL = "COMMON_GET_CITIES_FAIL";

// client types
export const COMMON_GET_RESERVATIONS_START = "COMMON_GET_RESERVATIONS_START";
export const COMMON_GET_RESERVATIONS_SUCCESS = "COMMON_GET_RESERVATIONS_SUCCESS";
export const COMMON_GET_RESERVATIONS_FAIL = "COMMON_GET_RESERVATIONS_FAIL";

export const COMMON_CREATE_RESERVATION_START = "COMMON_CREATE_RESERVATION_START";
export const COMMON_CREATE_RESERVATION_SUCCESS = "COMMON_CREATE_RESERVATION_SUCCESS";
export const COMMON_CREATE_RESERVATION_FAIL = "COMMON_CREATE_RESERVATION_FAIL";

export const COMMON_DELETE_RESERVATION_START = "COMMON_DELETE_RESERVATION_START";
export const COMMON_DELETE_RESERVATION_SUCCESS = "COMMON_DELETE_RESERVATION_SUCCESS";
export const COMMON_DELETE_RESERVATION_FAIL = "COMMON_DELETE_RESERVATION_FAIL";