
// types for user
export const USER_REGISTER_START = "USER_REGISTER_START";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGIN_START = "USER_LOGIN_START";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_GET_START = "USER_GET_START";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";
export const USER_GET_FAIL = "USER_GET_FAIL";

export const USER_PROFILE_UPDATE_START = "USER_PROFILE_UPDATE_START";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_FAIL = "USER_PROFILE_UPDATE_FAIL";

// types for management
export const MANAGEMENT_GET_LOCATIONS_START = "MANAGEMENT_GET_LOCATIONS_START";
export const MANAGEMENT_GET_LOCATIONS_SUCCESS = "MANAGEMENT_GET_LOCATIONS_SUCCESS";
export const MANAGEMENT_GET_LOCATIONS_FAIL = "MANAGEMENT_GET_LOCATIONS_FAIL";

export const MANAGEMENT_LOCATIONS_CREATE_START = "MANAGEMENT_LOCATIONS_CREATE_START";
export const MANAGEMENT_LOCATIONS_CREATE_SUCCESS = "MANAGEMENT_LOCATIONS_CREATE_SUCCESS";
export const MANAGEMENT_LOCATIONS_CREATE_FAIL = "MANAGEMENT_LOCATIONS_CREATE_FAIL";

export const MANAGEMENT_LOCATIONS_UPDATE_START = "MANAGEMENT_LOCATIONS_UPDATE_START";
export const MANAGEMENT_LOCATIONS_UPDATE_SUCCESS = "MANAGEMENT_LOCATIONS_UPDATE_SUCCESS";
export const MANAGEMENT_LOCATIONS_UPDATE_FAIL = "MANAGEMENT_LOCATIONS_UPDATE_FAIL";

export const MANAGEMENT_GET_SCHEDULE_START = "MANAGEMENT_GET_SCHEDULE_START";
export const MANAGEMENT_GET_SCHEDULE_SUCCESS = "MANAGEMENT_GET_SCHEDULE_SUCCESS";
export const MANAGEMENT_GET_SCHEDULE_FAIL = "MANAGEMENT_GET_SCHEDULE_FAIL";

export const MANAGEMENT_GET_LOCATION_COURTS_START = "MANAGEMENT_GET_LOCATION_COURTS_START";
export const MANAGEMENT_GET_LOCATION_COURTS_SUCCESS = "MANAGEMENT_GET_LOCATION_COURTS_SUCCESS";
export const MANAGEMENT_GET_LOCATION_COURTS_FAIL = "MANAGEMENT_GET_LOCATION_COURTS_FAIL";

// common types for users, companies
export const COMMON_GET_COMPANIES_START = "COMMON_GET_COMPANIES_START";
export const COMMON_GET_COMPANIES_SUCCESS = "COMMON_GET_COMPANIES_SUCCESS";
export const COMMON_GET_COMPANIES_FAIL = "COMMON_GET_COMPANIES_FAIL";

export const COMMON_GET_COURT_TYPES_START = "COMMON_GET_COURT_TYPES_START";
export const COMMON_GET_COURT_TYPES_SUCCESS = "COMMON_GET_COURT_TYPES_SUCCESS";
export const COMMON_GET_COURT_TYPES_FAIL = "COMMON_GET_COURT_TYPES_FAIL";

export const COMMON_GET_LOCATIONS_START = "COMMON_GET_LOCATIONS_START";
export const COMMON_GET_LOCATIONS_SUCCESS = "COMMON_GET_LOCATIONS_SUCCESS";
export const COMMON_GET_LOCATIONS_FAIL = "COMMON_GET_LOCATIONS_FAIL";

export const COMMON_GET_COURTS_START = "COMMON_GET_COURTS_START";
export const COMMON_GET_COURTS_SUCCESS = "COMMON_GET_COURTS_SUCCESS";
export const COMMON_GET_COURTS_FAIL = "COMMON_GET_COURTS_FAIL";